INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (57,'ESTRUTURAS ORGANIZACIONAIS',1),
	 (58,'FILOSOFIA E ÉTICA',1),
	 (59,'NOÇÕES DE ENGENHARIA DE SOFTWARE',1),
	 (60,'INTRODUÇÃO À LÓGICA',1),
	 (61,'NOÇÕES BÁSICAS DE PROGRAMAÇÃO',1),
	 (62,'PORTUGUÊS INSTRUMENTAL',1),
	 (63,'ESTATÍSTICA E PROBABILIDADE',1),
	 (64,'CÁLCULO DIFERENCIAL E INTEGRAL A',1),
	 (65,'ANÁLISE DE SISTEMAS I',1),
	 (66,'ORGANIZAÇÃO DE COMPUTADORES I',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (67,'PROGRAMAÇÃO DE COMPUTADORES I',1),
	 (68,'FUNDAMENTOS DA CONTABILIDADE',1),
	 (69,'INFERÊNCIA ESTATÍSTICA',1),
	 (71,'ANÁLISE DE SISTEMAS II',1),
	 (72,'ORGANIZAÇÃO DE COMPUTADORES II',1),
	 (73,'PROGRAMAÇÃO DE COMPUTADORES II',1),
	 (74,'METODOLOGIA DA PESQUISA',1),
	 (75,'CÁLCULO NUMÉRICO (S.I.)',1),
	 (76,'MATEMÁTICA DISCRETA',1),
	 (77,'PROJETO DE SISTEMAS I',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (78,'GERÊNCIA DE PROJETOS',1),
	 (79,'ESTRUTURA DE DADOS I',1),
	 (80,'ÁLGEBRA LINEAR',1),
	 (81,'BANCO DE DADOS I',1),
	 (82,'PROJETO DE SISTEMAS II',1),
	 (83,'PROGRAMAÇÃO DE COMPUTADORES III',1),
	 (84,'QUALIDADE DE SOFTWARE',1),
	 (85,'ESTRUTURA DE DADOS II',1),
	 (86,'PESQUISA OPERACIONAL I',1),
	 (70,'CÁLCULO DIFERENCIAL E INTEGRAL B',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (87,'BANCO DE DADOS II',1),
	 (88,'UX E DESENVOLVIMENTO WEB',1),
	 (89,'SIST. DE INFORM. GERENCIAIS',1),
	 (90,'SISTEMAS OPERACIONAIS I',1),
	 (91,'GERÊNCIA DE SIST. E PROJETOS',1),
	 (92,'DESENVOLVIMENTO DE SISTEMAS I',1),
	 (93,'DESENVOLVIMENTO PARA DISPOSITIVOS MOVEIS',1),
	 (94,'INTRODUÇÃO A REDES DE COMPUTADORES',1),
	 (95,'SISTEMAS OPERACIONAIS II',1),
	 (96,'TRABALHO DE CONCLUÃO DE CURSO I',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (97,'ESTÁGIO SUPERVISIONADO I',1),
	 (98,'ESTÁGIO SUPERVISIONADO II',1),
	 (99,'DESENVOLVIMENTO DE SISTEMAS II',1),
	 (100,'BANCO DE DAOOS III',1),
	 (101,'GESTÃO DE REDES',1),
	 (102,'EMPREENDEDORISMO E GESTÃO ESTRATÉGICA',1),
	 (103,'GERÊNCIA EM INFORMAÇÃO',1),
	 (104,'TRABALHO DE CONCLUÃO DE CURSO II',1);
