INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (57,'ESTRUTURAS ORGANIZACIONAIS',1),
	 (58,'FILOSOFIA E ÉTICA',1),
	 (59,'NOÇÕES DE ENGENHARIA DE SOFTWARE',1),
	 (60,'INTRODUÇÃO À LÓGICA',1),
	 (61,'NOÇÕES BÁSICAS DE PROGRAMAÇÃO',1),
	 (62,'PORTUGUÊS INSTRUMENTAL',1),
	 (63,'ESTATÍSTICA E PROBABILIDADE',1),
	 (64,'CÁLCULO DIFERENCIAL E INTEGRAL A',1),
	 (65,'ANÁLISE DE SISTEMAS I',1),
	 (66,'ORGANIZAÇÃO DE COMPUTADORES I',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (67,'PROGRAMAÇÃO DE COMPUTADORES I',1),
	 (68,'FUNDAMENTOS DA CONTABILIDADE',1),
	 (69,'INFERÊNCIA ESTATÍSTICA',1),
	 (71,'ANÁLISE DE SISTEMAS II',1),
	 (72,'ORGANIZAÇÃO DE COMPUTADORES II',1),
	 (73,'PROGRAMAÇÃO DE COMPUTADORES II',1),
	 (74,'METODOLOGIA DA PESQUISA',1),
	 (75,'CÁLCULO NUMÉRICO (S.I.)',1),
	 (76,'MATEMÁTICA DISCRETA',1),
	 (77,'PROJETO DE SISTEMAS I',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (78,'GERÊNCIA DE PROJETOS',1),
	 (79,'ESTRUTURA DE DADOS I',1),
	 (80,'ÁLGEBRA LINEAR',1),
	 (81,'BANCO DE DADOS I',1),
	 (82,'PROJETO DE SISTEMAS II',1),
	 (83,'PROGRAMAÇÃO DE COMPUTADORES III',1),
	 (84,'QUALIDADE DE SOFTWARE',1),
	 (85,'ESTRUTURA DE DADOS II',1),
	 (86,'PESQUISA OPERACIONAL I',1),
	 (70,'CÁLCULO DIFERENCIAL E INTEGRAL B',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (87,'BANCO DE DADOS II',1),
	 (88,'UX E DESENVOLVIMENTO WEB',1),
	 (89,'SIST. DE INFORM. GERENCIAIS',1),
	 (90,'SISTEMAS OPERACIONAIS I',1),
	 (91,'GERÊNCIA DE SIST. E PROJETOS',1),
	 (92,'DESENVOLVIMENTO DE SISTEMAS I',1),
	 (93,'DESENVOLVIMENTO PARA DISPOSITIVOS MOVEIS',1),
	 (94,'INTRODUÇÃO A REDES DE COMPUTADORES',1),
	 (95,'SISTEMAS OPERACIONAIS II',1),
	 (96,'TRABALHO DE CONCLUÃO DE CURSO I',1);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (97,'ESTÁGIO SUPERVISIONADO I',1),
	 (98,'ESTÁGIO SUPERVISIONADO II',1),
	 (99,'DESENVOLVIMENTO DE SISTEMAS II',1),
	 (100,'BANCO DE DAOOS III',1),
	 (101,'GESTÃO DE REDES',1),
	 (102,'EMPREENDEDORISMO E GESTÃO ESTRATÉGICA',1),
	 (103,'GERÊNCIA EM INFORMAÇÃO',1),
	 (104,'TRABALHO DE CONCLUÃO DE CURSO II',1);


-- Matemática
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (105,'FUNDAMENTOS DE MATEMÁTICA ELEMENTAR I',2),
	 (106,'MATEMÁTICA BÁSICA I',2),
	 (107,'GEOMETRIA I',2),
	 (108,'PORTUGUÊS INSTRUMENTAL',2),
	 (109,'LIBRAS',2),
	 (110,'FILOSOFIA DA EDUCAÇÃO',2),
	 (111,'FUNDAMENTOS DE MATEMÁTICA ELEMENTAR II',2),
	 (112,'MATEMÁTICA BÁSICA II',2),
	 (113,'GEOMETRIA II',2),
	 (114,'POLÍTICAS DE GESTÃO E ORGANIZAÇÃO DA EDUCACÃO NACIONAL',2);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES	 
	 (115,'INFORMÁTICA BÁSICA',2),
	 (116,'SOCIOLOGIA DA EDUCAÇÃO',2),
	 (117,'FUNDAMENTOS DE MATEMÁTICA ELEMENTAR III',2),
	 (118,'CÁLCULO DIFERENCIAL E INTEGRAL I',2),
	 (119,'GEOMETRIA ANALÍTICA',2),
	 (120,'METODOLOGIA DE PESQUISA ',2),
	 (121,'PLANEJAMENTO EDUCACIONAL E CURRÍCULO',2),
	 (122,'PSICOLOGIA DA EDUCAÇÃO',2),
	 (123,'INTRODUÇÃO À LÓGICA',2),
	 (124,'CÁLCULO DIFERENCIAL E INTEGRAL II',2);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (125,'ESTATÍSTICA E PROBABILIDADE',2),
	 (126,'EDUCAÇÃO PARA A INCLUSÃO',2),
	 (127,'DIDÁTICA',2),
	 (128,'ÁLGEBRA LINEAR ',2),
	 (129,'METODOLOGIAS PARA O ENSINO DA MATEMÁTICA I',2),
	 (130,'CÁLCULO DIFERENCIAL E INTEGRAL III',2),
	 (131,'INFERÊNCIA ESTATÍSTICA',2),
	 (132,'EDUCAÇÃO DE JOVENS E ADULTOS',2),
	 (133,'FÍSICA I',2),
	 (134,'ÁLGEBRA LINEAR E GEOMETRIA ANALÍTICA',2);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (135,'ESTÁGIO CURRICULAR SUPERVISIONADO I',2),
	 (136,'METODOLOGIAS PARA O ENSINO DA MATEMÁTICA II',2),
	 (137,'CÁLCULO DIFERENCIAL E INTEGRAL IV',2),
	 (138,'LABORATÓRIO DE PESQUISA EM EDUCAÇÃO MATEMÁTICA I',2),
	 (139,'CÁLCULO NUMÉRICO',2),
	 (140,'FÍSICA II',2),
	 (141,'EQUAÇÕES DIFERENCIAIS ORDINÁRIAS',2),
	 (142,'ESTÁGIO CURRICULAR SUPERVISIONADO II',2),
	 (143,'INTRODUÇÃO À ÁLGEBRA',2),
	 (144,'MATEMÁTICA COMPUTACIONAL',2);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES
	 (145,'LABORATÓRIO DE PESQUISA EM EDUCAÇÃO MATEMÁTICA II',2),
	 (146,'EDUCAÇÃO AMBIENTAL E CIDADANIA',2),
	 (147,'FÍSICA III',2),
	 (148,'MATEMÁTICA DISCRETA',2),
	 (149,'ESTÁGIO CURRICULAR SUPERVISIONADO III',2),
	 (150,'TRABALHO DE CONCLUSÃO DE CURSO I',2),
	 (151,'MATEMÁTICA FINANCEIRA',2),
	 (152,'ANÁLISE REAL',2),
	 (153,'HISTÓRIA E FILOSOFIA DA MATEMÁTICA',2),
	 (154,'ÉTICA, DIVERSIDADE E DIREITOS HUMANOS',2);
INSERT INTO public.disciplina (id,nome,idcurso) VALUES	
	 (155,'FÍSICA IV',2),
	 (156,'TECNOLOGIAS NO ENSINO DA MATEMÁTICA',2),
	 (157,'ESTÁGIO CURRICULAR SUPERVISIONADO IV',2),
	 (158,'TRABALHO DE CONCLUSÃO DECURSO II',2);

--Administração
