INSERT INTO professor (nome) VALUES ('Afonso Carlos Tavares Pinheiro');
INSERT INTO professor (nome) VALUES ('Alan Carvalho Galante');
INSERT INTO professor (nome) VALUES ('Alan Lopes Campos');
INSERT INTO professor (nome) VALUES ('Alfredo Luiz Pessanha Manhães');
INSERT INTO professor (nome) VALUES ('André Luiz Gonçalves da Silva');
INSERT INTO professor (nome) VALUES ('Ana Maria da Mota Moura');
INSERT INTO professor (nome) VALUES ('Braúlio Ferreira de Carvalho');
INSERT INTO professor (nome) VALUES ('Carlos Eduardo Lopes da Silva');
INSERT INTO professor (nome) VALUES ('Douglas Valiati');
INSERT INTO professor (nome) VALUES ('Edson Ricardo Gonçalves');
INSERT INTO professor (nome) VALUES ('Edwin Benito Mitacc Meza');
INSERT INTO professor (nome) VALUES ('Fernanda Antunes Gomes da Costa');
INSERT INTO professor (nome) VALUES ('Henrique Oswaldo Uzêda Pereira de Souza');
INSERT INTO professor (nome) VALUES ('Irineu Azevedo Lima Neto');
INSERT INTO professor (nome) VALUES ('Isac Mendes Lacerda');
INSERT INTO professor (nome) VALUES ('José Carlos Rocha Pereira Júnior');
INSERT INTO professor (nome) VALUES ('Leonard Barreto Moreira');
INSERT INTO professor (nome) VALUES ('Luciano Garcia Mangueira');
INSERT INTO professor (nome) VALUES ('Maurício Natividade de Oliveira Fernandes');
INSERT INTO professor (nome) VALUES ('Rogério Ferreira Moraes');
INSERT INTO professor (nome) VALUES ('Roque André Ciufo Poeys');
INSERT INTO professor (nome) VALUES ('Sérgio Eduardo Corrêa Neto');
INSERT INTO professor (nome) VALUES ('Sérgio Pereira Gonçalves');
INSERT INTO professor (nome) VALUES ('Simone Luiza Sermoud');
INSERT INTO professor (nome) VALUES ('Soraya Aparecida da Rocha Jorge');
INSERT INTO professor (nome) VALUES ('Wagner Miquéias Felix Damasceno');
